#   This file is part of Indexor.
#
#    Indexor is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Indexor is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Indexor.  If not, see <http://www.gnu.org/licenses/>.

import sys

if sys.platform == "win32":
    SEPARATOR = "\\"
else:
    SEPARATOR = "/"


VERSION = "v0.1-alpha2"
SITE = "http://www.vicarious.com.ar/blogs/indexor.php"
AUTHOR = "Juan Manuel Santos"
EMAIL = "godlike64 at gm4il d0t c0m"
DESC = "A file and directory indexing tool."

NO_INFO = "No information available"

MIMES = {
        "audio/basic"                                   :   "audio",
        "audio/flac"                                    :   "audio",
        "audio/midi"                                    :   "audio",
        "audio/mpeg"                                    :   "audio",
        "audio/ogg"                                     :   "audio",
        "audio/x-aiff"                                  :   "audio",
        "audio/x-mpegurl"                               :   "audio",
        "audio/x-ms-wma"                                :   "audio",
        "audio/x-musepack"                              :   "audio",
        "audio/x-scpls"                                 :   "audio",
        "audio/x-spc"                                   :   "audio",
        "audio/x-wav"                                   :   "audio",
        "application/base64"                            :   "executable",
        "application/java-archive"                      :   "archive",
        "application/java-serialized-object"            :   "executable",
        "application/java-vm"                           :   "executable",
        "application/json"                              :   "source",
        "application/mathematica"                       :   "ascii",
        "application/msword"                            :   "document",
        "application/octet-stream"                      :   "executable",
        "application/ogg"                               :   "audio",
        "application/pdf"                               :   "document",
        "application/pgp-keys"                          :   "security",
        "application/pgp-signature"                     :   "security",
        "application/pics-rules"                        :   "file",
        "application/postscript"                        :   "print",
        "application/rar"                               :   "archive",
        "application/relax-ng-compact-syntax"           :   "html",
        "application/rdf+xml"                           :   "html",
        "application/rtf"                               :   "document",
        "application/sparql-results+xml"                :   "html",
        "application/vnd.lotus-organizer"               :   "html",
        "application/vnd.mozilla.xul+xml"               :   "html",
        "application/vnd.ms-cab-compressed"             :   "archive",
        "application/vnd.ms-excel"                      :   "spreadsheet",
        "application/vnd.ms-excel.sheet." +
        "macroenabled.12"                               :   "spreadsheet",
        "application/vnd.ms-pki.seccat"                 :   "archive",
        "application/vnd.ms-powerpoint"                 :   "presentation",
        "application/vnd.oasis.opendocument.database"   :   "document",
        "application/vnd.oasis.opendocument.formula"    :   "document",
        "application/vnd.oasis.opendocument." +
        "presentation"                                  :   "presentation",
        "application/vnd.oasis.opendocument." +
        "spreadsheet"                                   :   "spreadsheet",
        "application/vnd.oasis.opendocument.text"       :   "document",
        "application/vnd.openxmlformats-" +
        "officedocument.presentationml.presentation"    :   "presentation",
        "application/vnd.openxmlformats-" +
        "officedocument.spreadsheetml.sheet"            :   "spreadsheet",
        "application/vnd.openxmlformats-" +
        "officedocument.wordprocessingml.document"      :   "document",
        "application/vnd.palm"                          :   "executable",
        "application/vnd.visio"                         :   "drawing",
        "application/winhlp"                            :   "help",
        "application/wsdl+xml"                          :   "html",
        "application/x-bittorrent"                      :   "archive",
        "application/x-bzip"                            :   "archive",
        "application/x-bzip2"                           :   "archive",
        "application/x-bzip-compressed-tar"             :   "archive",
        "application/x-bzip-compressed-tar"             :   "archive",
        "application/x-bcpio"                           :   "archive",
        "application/x-cdlink"                          :   "optical",
        "application/xspf+xml"                          :   "html",
        "text/x-c"                                      :   "source",
        "application/x-chm"                             :   "help",
        "application/x-cpio"                            :   "archive",
        "application/x-csh"                             :   "script",
        "application/x-debian-package"                  :   "archive",
        "application/x-director"                        :   "internet",
        "application/x-dtbresource+xml"                 :   "html",
        "application/x-flac"                            :   "audio",
        "application/x-font"                            :   "font",
        "application/x-font-type1"                      :   "font",
        "application/x-font-ttf"                        :   "font",
        "application/x-genesis-rom"                     :   "game",
        "application/x-glade"                           :   "glade",
        "application/x-graphing-calculator"             :   "calc",
        "application/x-gzip"                            :   "archive",
        "application/x-internet-signup"                 :   "internet",
        "application/x-iso9660-image"                   :   "optical",
        "application/x-javascript"                      :   "html",
        "application/x-maker"                           :   "script",
        "application/x-mif"                             :   "mail",
        "application/x-msaccess"                        :   "document",
        "application/x-msdos-program"                   :   "script",
        "application/x-msdownload"                      :   "executable",
        "application/x-msi"                             :   "executable",
        "application/x-mswrite"                         :   "document",
        "application/x-netcdf"                          :   "browser",
        "application/x-object"                          :   "file",
        "application/x-php"                             :   "html",
        "application/x-pn-realaudio"                    :   "audio",
        "application/x-pkcs7-crl"                       :   "certificate",
        "application/x-python-code"                     :   "script",
        "application/x-rar-compressed"                  :   "archive",
        "application/x-redhat-package-manager"          :   "archive",
        "application/x-sh"                              :   "script",
        "application/x-shockwave-flash"                 :   "video",
        "application/x-ssh-key"                         :   "security",
        "application/x-subrip"                          :   "ascii",
        "application/x-tar"                             :   "archive",
        "application/x-tcl"                             :   "executable",
        "application/x-tex"                             :   "ascii",
        "application/x-trash"                           :   "trash",
        "application/x-troff"                           :   "ascii",
        "application/x-troff-man"                       :   "ascii",
        "application/x-troff-me"                        :   "ascii",
        "application/x-troff-ms"                        :   "ascii",
        "application/x-wais-source"                     :   "executable",
        "application/x-x509-ca-cert"                    :   "certificate",
        "application/x-xcf"                             :   "image",
        "application/x-xfig"                            :   "image",
        "application/x-xpinstall"                       :   "executable",
        "application/xhtml+xml"                         :   "html",
        "application/xml"                               :   "html",
        "application/xml-dtd"                           :   "html",
        "application/xslt+xml"                          :   "html",
        "application/zip"                               :   "archive",
        "chemical/x-crossfire"                          :   "file",
        "chemical/x-gamess-input"                       :   "file",
        "chemical/x-gaussian-log"                       :   "file",
        "chemical/x-mdl-sdfile"                         :   "file",
        "chemical/x-pdb"                                :   "file",
        "chemical/x-xyz"                                :   "file",
        "image/x-corelphotopaint"                       :   "image",
        "image/gif"                                     :   "image",
        "image/jpeg"                                    :   "image",
        "image/pict"                                    :   "image",
        "image/png"                                     :   "image",
        "image/svg+xml"                                 :   "image",
        "image/tiff"                                    :   "image",
        "image/vnd.djvu"                                :   "image",
        "image/x-icon"                                  :   "image",
        "image/x-ms-bmp"                                :   "image",
        "image/x-photoshop"                             :   "image",
        "image/x-portable-bitmap"                       :   "image",
        "image/x-portable-pixmap"                       :   "image",
        "image/x-xbitmap"                               :   "image",
        "image/x-xpixmap"                               :   "image",
        "image/x-tga"                                   :   "image",
        "inode/folder"                                  :   "folder",
        "message/rfc822"                                :   "mail",
        "text/cache"                                    :   "ascii",
        "text/calendar"                                 :   "calendar",
        "text/comma-separated-values"                   :   "ascii",
        "text/css"                                      :   "html",
        "text/csv"                                      :   "ascii",
        "text/html"                                     :   "html",
        "text/plain"                                    :   "ascii",
        "text/rtf"                                      :   "document",
        "text/sgml"                                     :   "html",
        "text/texmacs"                                  :   "document",
        "text/troff"                                    :   "document",
        "text/vnd.fmi.flexstor"                         :   "text",
        "text/x-asm"                                    :   "source",
        "text/x-bibtex"                                 :   "text",
        "text/x-c++hdr"                                 :   "source",
        "text/x-c++src"                                 :   "source",
        "text/x-chdr"                                   :   "script",
        "text/x-csrc"                                   :   "source",
        "text/x-fortran"                                :   "source",
        "text/x-haskell"                                :   "source",
        "text/x-perl"                                   :   "script",
        "text/x-subviewer"                              :   "ascii",
        "text/x-java"                                   :   "source",
        "text/x-java-source"                            :   "source",
        "text/x-moc"                                    :   "source",
        "text/x-psp"                                    :   "ascii",
        "text/x-python"                                 :   "script",
        "text/x-sgml"                                   :   "html",
        "text/x-sh"                                     :   "script",
        "text/x-tex"                                    :   "document",
        "text/x-tcl"                                    :   "source",
        "text/x-vcalendar"                              :   "calendar",
        "text/x-vcard"                                  :   "ascii",
        "text/vnd.sun.j2me.app-descriptor"              :   "archive",
        "text/xml"                                      :   "html",
        "text/xul"                                      :   "html",
        "video/3gpp"                                    :   "video",
        "video/mp4"                                     :   "video",
        "video/mpeg"                                    :   "video",
        "video/quicktime"                               :   "video",
        "video/ogg"                                     :   "video",
        "video/x-flv"                                   :   "video",
        "video/x-matroska"                              :   "video",
        "video/x-mng"                                   :   "video",
        "video/x-ms-asf"                                :   "video",
        "video/x-ms-wmv"                                :   "video",
        "video/x-msvideo"                               :   "video",
        }

ICONS = {
        "ascii"                 :   "text-x-generic",
            "archive"           :   "package-x-generic",
            "audio"             :   "audio-x-generic",
            "calc"              :   "accessories-calculator",
            "calendar"          :   "x-office-calendar",
            "certificate"       :   "application-certificate",
            "browser"           :   "browser",
            "disk"              :   "drive-harddisk",
            "document"          :   "x-office-document",
            "document-template" :   "x-office-document-template",
            "drawing"           :   "x-office-drawing",
            "executable"        :   "application-x-executable",
            "file"              :   "text-x-generic",
            "font"              :   "font-x-generic",
            "folder"            :   "folder",
            "game"              :   "applications-games",
            "glade"             :   "preferences-system-session",
            "help"              :   "help-browser",
            "html"              :   "text-html",
            "image"             :   "image-x-generic",
            "internet"          :   "applications-internet",
            "mail"              :   "internet-mail",
            "optical"           :   "media-optical",
            "print"             :   "document-print",
            "presentation"      :   "x-office-presentation",
            "security"          :   "system-lock-screen",
            "script"            :   "text-x-script",
            "source"            :   "text-x-generic",
            "spreadsheet"       :   "x-office-spreadsheet",
            "trash"             :   "user-trash",
            "video"             :   "video-x-generic",
         }

NOT_AUDIO = [
             "audio/basic",
             "audio/x-mpegurl",
             "audio/x-scpls",
             "audio/x-spc",
             "audio/midi"
             ]
